/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DoctorId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LogId = IDL.Nat;
export const UserId = IDL.Nat;
export const AccessType = IDL.Variant({
  'manual_id' : IDL.Null,
  'qr_scan' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const AccessLog = IDL.Record({
  'id' : LogId,
  'doctorId' : DoctorId,
  'patientId' : UserId,
  'accessType' : AccessType,
  'accessedAt' : Timestamp,
});
export const DoctorStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
  'suspended' : IDL.Null,
});
export const DoctorProfile = IDL.Record({
  'id' : DoctorId,
  'status' : DoctorStatus,
  'name' : IDL.Text,
  'rejectionReason' : IDL.Opt(IDL.Text),
  'reviewedAt' : IDL.Opt(Timestamp),
  'reviewedBy' : IDL.Opt(IDL.Principal),
  'email' : IDL.Text,
  'specialty' : IDL.Text,
  'licenseNumber' : IDL.Text,
  'hospitalName' : IDL.Text,
  'principalId' : IDL.Principal,
  'requestedAt' : Timestamp,
  'contactPhone' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'totalPatients' : IDL.Nat,
  'totalAccessLogs' : IDL.Nat,
  'pendingRequests' : IDL.Nat,
  'totalDoctors' : IDL.Nat,
});
export const EmergencyContact = IDL.Record({
  'relationship' : IDL.Text,
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const Medication = IDL.Record({
  'dosage' : IDL.Text,
  'name' : IDL.Text,
  'frequency' : IDL.Text,
});
export const PatientProfile = IDL.Record({
  'id' : UserId,
  'age' : IDL.Nat,
  'emergencyId' : IDL.Text,
  'insuranceProvider' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'insurancePolicyNumber' : IDL.Text,
  'emergencyContacts' : IDL.Vec(EmergencyContact),
  'updatedAt' : Timestamp,
  'medicalHistory' : IDL.Text,
  'bloodGroup' : IDL.Text,
  'chronicDiseases' : IDL.Vec(IDL.Text),
  'profilePhotoUrl' : IDL.Text,
  'allergies' : IDL.Vec(IDL.Text),
  'principalId' : IDL.Principal,
  'currentMedications' : IDL.Vec(Medication),
});
export const PatientEmergencyInfo = IDL.Record({
  'age' : IDL.Nat,
  'insuranceProvider' : IDL.Text,
  'name' : IDL.Text,
  'insurancePolicyNumber' : IDL.Text,
  'emergencyContacts' : IDL.Vec(EmergencyContact),
  'bloodGroup' : IDL.Text,
  'chronicDiseases' : IDL.Vec(IDL.Text),
  'allergies' : IDL.Vec(IDL.Text),
  'currentMedications' : IDL.Vec(Medication),
});
export const RegisterPatientInput = IDL.Record({
  'age' : IDL.Nat,
  'insuranceProvider' : IDL.Text,
  'name' : IDL.Text,
  'insurancePolicyNumber' : IDL.Text,
  'emergencyContacts' : IDL.Vec(EmergencyContact),
  'medicalHistory' : IDL.Text,
  'bloodGroup' : IDL.Text,
  'chronicDiseases' : IDL.Vec(IDL.Text),
  'profilePhotoUrl' : IDL.Text,
  'allergies' : IDL.Vec(IDL.Text),
  'currentMedications' : IDL.Vec(Medication),
});
export const SubmitDoctorRequestInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'specialty' : IDL.Text,
  'licenseNumber' : IDL.Text,
  'hospitalName' : IDL.Text,
  'contactPhone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'approveDoctorRequest' : IDL.Func([DoctorId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'generateEmergencyId' : IDL.Func([], [IDL.Text], []),
  'getAccessLogs' : IDL.Func([], [IDL.Vec(AccessLog)], ['query']),
  'getAllDoctors' : IDL.Func([], [IDL.Vec(DoctorProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getDoctorProfile' : IDL.Func([], [IDL.Opt(DoctorProfile)], ['query']),
  'getDoctorStatus' : IDL.Func([], [IDL.Opt(DoctorProfile)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(PatientProfile)], ['query']),
  'getPatientByEmergencyId' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PatientProfile)],
      ['query'],
    ),
  'getPatientEmergencyInfo' : IDL.Func(
      [IDL.Text, AccessType],
      [IDL.Opt(PatientEmergencyInfo)],
      [],
    ),
  'getPendingDoctorRequests' : IDL.Func(
      [],
      [IDL.Vec(DoctorProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerPatient' : IDL.Func([RegisterPatientInput], [PatientProfile], []),
  'rejectDoctorRequest' : IDL.Func([DoctorId, IDL.Text], [], []),
  'submitDoctorRequest' : IDL.Func(
      [SubmitDoctorRequestInput],
      [DoctorProfile],
      [],
    ),
  'suspendDoctor' : IDL.Func([DoctorId], [], []),
  'updatePatientProfile' : IDL.Func(
      [RegisterPatientInput],
      [PatientProfile],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DoctorId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LogId = IDL.Nat;
  const UserId = IDL.Nat;
  const AccessType = IDL.Variant({
    'manual_id' : IDL.Null,
    'qr_scan' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const AccessLog = IDL.Record({
    'id' : LogId,
    'doctorId' : DoctorId,
    'patientId' : UserId,
    'accessType' : AccessType,
    'accessedAt' : Timestamp,
  });
  const DoctorStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
    'suspended' : IDL.Null,
  });
  const DoctorProfile = IDL.Record({
    'id' : DoctorId,
    'status' : DoctorStatus,
    'name' : IDL.Text,
    'rejectionReason' : IDL.Opt(IDL.Text),
    'reviewedAt' : IDL.Opt(Timestamp),
    'reviewedBy' : IDL.Opt(IDL.Principal),
    'email' : IDL.Text,
    'specialty' : IDL.Text,
    'licenseNumber' : IDL.Text,
    'hospitalName' : IDL.Text,
    'principalId' : IDL.Principal,
    'requestedAt' : Timestamp,
    'contactPhone' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'totalPatients' : IDL.Nat,
    'totalAccessLogs' : IDL.Nat,
    'pendingRequests' : IDL.Nat,
    'totalDoctors' : IDL.Nat,
  });
  const EmergencyContact = IDL.Record({
    'relationship' : IDL.Text,
    'name' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Medication = IDL.Record({
    'dosage' : IDL.Text,
    'name' : IDL.Text,
    'frequency' : IDL.Text,
  });
  const PatientProfile = IDL.Record({
    'id' : UserId,
    'age' : IDL.Nat,
    'emergencyId' : IDL.Text,
    'insuranceProvider' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'insurancePolicyNumber' : IDL.Text,
    'emergencyContacts' : IDL.Vec(EmergencyContact),
    'updatedAt' : Timestamp,
    'medicalHistory' : IDL.Text,
    'bloodGroup' : IDL.Text,
    'chronicDiseases' : IDL.Vec(IDL.Text),
    'profilePhotoUrl' : IDL.Text,
    'allergies' : IDL.Vec(IDL.Text),
    'principalId' : IDL.Principal,
    'currentMedications' : IDL.Vec(Medication),
  });
  const PatientEmergencyInfo = IDL.Record({
    'age' : IDL.Nat,
    'insuranceProvider' : IDL.Text,
    'name' : IDL.Text,
    'insurancePolicyNumber' : IDL.Text,
    'emergencyContacts' : IDL.Vec(EmergencyContact),
    'bloodGroup' : IDL.Text,
    'chronicDiseases' : IDL.Vec(IDL.Text),
    'allergies' : IDL.Vec(IDL.Text),
    'currentMedications' : IDL.Vec(Medication),
  });
  const RegisterPatientInput = IDL.Record({
    'age' : IDL.Nat,
    'insuranceProvider' : IDL.Text,
    'name' : IDL.Text,
    'insurancePolicyNumber' : IDL.Text,
    'emergencyContacts' : IDL.Vec(EmergencyContact),
    'medicalHistory' : IDL.Text,
    'bloodGroup' : IDL.Text,
    'chronicDiseases' : IDL.Vec(IDL.Text),
    'profilePhotoUrl' : IDL.Text,
    'allergies' : IDL.Vec(IDL.Text),
    'currentMedications' : IDL.Vec(Medication),
  });
  const SubmitDoctorRequestInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'specialty' : IDL.Text,
    'licenseNumber' : IDL.Text,
    'hospitalName' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'approveDoctorRequest' : IDL.Func([DoctorId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'generateEmergencyId' : IDL.Func([], [IDL.Text], []),
    'getAccessLogs' : IDL.Func([], [IDL.Vec(AccessLog)], ['query']),
    'getAllDoctors' : IDL.Func([], [IDL.Vec(DoctorProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getDoctorProfile' : IDL.Func([], [IDL.Opt(DoctorProfile)], ['query']),
    'getDoctorStatus' : IDL.Func([], [IDL.Opt(DoctorProfile)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(PatientProfile)], ['query']),
    'getPatientByEmergencyId' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PatientProfile)],
        ['query'],
      ),
    'getPatientEmergencyInfo' : IDL.Func(
        [IDL.Text, AccessType],
        [IDL.Opt(PatientEmergencyInfo)],
        [],
      ),
    'getPendingDoctorRequests' : IDL.Func(
        [],
        [IDL.Vec(DoctorProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerPatient' : IDL.Func([RegisterPatientInput], [PatientProfile], []),
    'rejectDoctorRequest' : IDL.Func([DoctorId, IDL.Text], [], []),
    'submitDoctorRequest' : IDL.Func(
        [SubmitDoctorRequestInput],
        [DoctorProfile],
        [],
      ),
    'suspendDoctor' : IDL.Func([DoctorId], [], []),
    'updatePatientProfile' : IDL.Func(
        [RegisterPatientInput],
        [PatientProfile],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };