/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AccessLog {
  'id' : LogId,
  'doctorId' : DoctorId,
  'patientId' : UserId,
  'accessType' : AccessType,
  'accessedAt' : Timestamp,
}
export type AccessType = { 'manual_id' : null } |
  { 'qr_scan' : null };
export interface DashboardStats {
  'totalPatients' : bigint,
  'totalAccessLogs' : bigint,
  'pendingRequests' : bigint,
  'totalDoctors' : bigint,
}
export type DoctorId = bigint;
export interface DoctorProfile {
  'id' : DoctorId,
  'status' : DoctorStatus,
  'name' : string,
  'rejectionReason' : [] | [string],
  'reviewedAt' : [] | [Timestamp],
  'reviewedBy' : [] | [Principal],
  'email' : string,
  'specialty' : string,
  'licenseNumber' : string,
  'hospitalName' : string,
  'principalId' : Principal,
  'requestedAt' : Timestamp,
  'contactPhone' : string,
}
export type DoctorStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null } |
  { 'suspended' : null };
export interface EmergencyContact {
  'relationship' : string,
  'name' : string,
  'phone' : string,
}
export type LogId = bigint;
export interface Medication {
  'dosage' : string,
  'name' : string,
  'frequency' : string,
}
export interface PatientEmergencyInfo {
  'age' : bigint,
  'insuranceProvider' : string,
  'name' : string,
  'insurancePolicyNumber' : string,
  'emergencyContacts' : Array<EmergencyContact>,
  'bloodGroup' : string,
  'chronicDiseases' : Array<string>,
  'allergies' : Array<string>,
  'currentMedications' : Array<Medication>,
}
export interface PatientProfile {
  'id' : UserId,
  'age' : bigint,
  'emergencyId' : string,
  'insuranceProvider' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'insurancePolicyNumber' : string,
  'emergencyContacts' : Array<EmergencyContact>,
  'updatedAt' : Timestamp,
  'medicalHistory' : string,
  'bloodGroup' : string,
  'chronicDiseases' : Array<string>,
  'profilePhotoUrl' : string,
  'allergies' : Array<string>,
  'principalId' : Principal,
  'currentMedications' : Array<Medication>,
}
export interface RegisterPatientInput {
  'age' : bigint,
  'insuranceProvider' : string,
  'name' : string,
  'insurancePolicyNumber' : string,
  'emergencyContacts' : Array<EmergencyContact>,
  'medicalHistory' : string,
  'bloodGroup' : string,
  'chronicDiseases' : Array<string>,
  'profilePhotoUrl' : string,
  'allergies' : Array<string>,
  'currentMedications' : Array<Medication>,
}
export interface SubmitDoctorRequestInput {
  'name' : string,
  'email' : string,
  'specialty' : string,
  'licenseNumber' : string,
  'hospitalName' : string,
  'contactPhone' : string,
}
export type Timestamp = bigint;
export type UserId = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'approveDoctorRequest' : ActorMethod<[DoctorId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'generateEmergencyId' : ActorMethod<[], string>,
  'getAccessLogs' : ActorMethod<[], Array<AccessLog>>,
  'getAllDoctors' : ActorMethod<[], Array<DoctorProfile>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getDoctorProfile' : ActorMethod<[], [] | [DoctorProfile]>,
  'getDoctorStatus' : ActorMethod<[], [] | [DoctorProfile]>,
  'getMyProfile' : ActorMethod<[], [] | [PatientProfile]>,
  'getPatientByEmergencyId' : ActorMethod<[string], [] | [PatientProfile]>,
  'getPatientEmergencyInfo' : ActorMethod<
    [string, AccessType],
    [] | [PatientEmergencyInfo]
  >,
  'getPendingDoctorRequests' : ActorMethod<[], Array<DoctorProfile>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerPatient' : ActorMethod<[RegisterPatientInput], PatientProfile>,
  'rejectDoctorRequest' : ActorMethod<[DoctorId, string], undefined>,
  'submitDoctorRequest' : ActorMethod<
    [SubmitDoctorRequestInput],
    DoctorProfile
  >,
  'suspendDoctor' : ActorMethod<[DoctorId], undefined>,
  'updatePatientProfile' : ActorMethod<[RegisterPatientInput], PatientProfile>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];